### PR TITLE
Fixes in code preview plugin

### LINKED ISSUE #258: Code preview raises some exceptions
**Describe the bug / issue**
I have detected that code preview raises some exceptions and it should not raise them but show the error to the users. This is in `TaskPreviewFileAPI`

**To Reproduce**
Do not know yet when this happens but probably is when the course id is not correctly obtained.

**Expected behavior**
Rather than throwing exceptions, the error code and message should be returned.

### PR DESCRIPTION
**Pull request by crdgonzalezca**
# Description

Several bugs were detected and fixed, as well as some refactoring was done. The main bug was about raising an exception, as well as correctly setting the code template when the code was shown. It will also work for LTI tasks. 

Fixes #258 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Tested locally

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

File: inginious/frontend/plugins/code_preview/static/js/code_preview_load.js [hunk 1]
```diff
@@ -1,25 +1,131 @@
...
+        return;
+    }
+
+    const template = `
+    <div class="row" id="code-preview-${language}-row">
+        <div class="form-group col-xs-12">
+            <div class="col-xs-4">
+                <select class="form-control" readonly>
+                    <option selected>${getLanguageName(language)}</option>
+                </select>
```
Comment (AndresFelipeCastellanos) [inline inginious/frontend/plugins/code_preview/static/js/code_preview_load.js]: Maybe change these select element for the file language and set it as a static input just like in the file, since there's only an option to this select.

**Review by AndresFelipeCastellanos — CHANGES_REQUESTED** [review]
I think the changes are right. I have a little suggestion of what we discussed.

**Comment by crdgonzalezca** [comment]
@AndresFelipeCastellanos and @Heldeg, please review my PR.

**Review by AndresFelipeCastellanos — APPROVED** [review]
The new changes looks good. I tested them locally and works fine.
